 version: 2
 jobs:
   build:
     machine:
       image: ubuntu-1604:201903-01
     steps:
       - checkout                              # Get the source code.
       - run: docker pull postgres:11.1-alpine # Download the DB image used in tests.
       - run:
           name: Run tests
           command: go test -v ./...
