[LoginOK]
hash = "sha1-bda53064173f51f95c7edb3903d4d51a8e610536"
other = "Успешно влезохте в системата."

[LogoutOK]
hash = "sha1-c65ebe3404d68fe993025f2e1d96d61a274ed9b0"
other = "Успешно излезохте от системата."

[UserCreateOK]
hash = "sha1-8231d82a09079ad75517da706a3cedb1e35a053f"
other = "Успешно създадохте нов потребител."

[UserDeleteOK]
hash = "sha1-1cb62798b2ac6f7f579c662d51d648aa66069e8a"
other = "Успешно изтирихте потребителя."

[UserUpdateOK]
hash = "sha1-463e3324121ebf9f40abc3d7671e260c87ad0b94"
other = "успешно актуализирахте потребителя."
